package com.uasfleet.order.domain.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * =============================================================================
 * DeliveryRoute Entity — Optimized Delivery Path
 * =============================================================================
 * Maps to the 'delivery_route' table in order_db. Stores the optimized
 * route generated by the Python dispatch-engine (VRP solver).
 *
 * WAYPOINTS FORMAT (JSONB):
 *   [{"lat": -6.200, "lng": 106.816, "alt": 100}, ...]
 *
 * RELATIONSHIP: delivery_route 1 ←→ 1 logistics_order
 * =============================================================================
 */
@Entity
@Table(name = "delivery_route")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class DeliveryRoute {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "order_id", unique = true, nullable = false)
    private LogisticsOrder order;

    @Column(name = "waypoints_json", nullable = false, columnDefinition = "jsonb")
    @JdbcTypeCode(SqlTypes.JSON)
    private String waypointsJson;

    @Column(name = "estimated_distance_km", precision = 8, scale = 2)
    private BigDecimal estimatedDistanceKm;

    @Column(name = "estimated_duration_min", precision = 8, scale = 2)
    private BigDecimal estimatedDurationMin;

    @Column(name = "actual_distance_km", precision = 8, scale = 2)
    private BigDecimal actualDistanceKm;

    @Column(name = "actual_duration_min", precision = 8, scale = 2)
    private BigDecimal actualDurationMin;

    @Column(name = "optimization_algorithm", length = 50)
    @Builder.Default
    private String optimizationAlgorithm = "VRP_ORTOOLS";

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;
}
